# Generated by Django 3.1.7 on 2021-05-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
