# Generated by Django 3.1.7 on 2021-04-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Setting',
        ),
    ]
