# Generated by Django 3.1.7 on 2021-05-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sliderphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
    ]
