# Generated by Django 3.1.7 on 2021-05-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sliderphoto_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderPhoto',
        ),
    ]
